
# Celery Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: finance-dev
spec:
  replicas: 1  # Можно масштабировать количество воркеров
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: worker
        image: freenance:{{IMAGE_TAG}}
        command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "700Mi"
            cpu: "100m"
# ---
# # Celery Flower Service (мониторинг)
# apiVersion: v1
# kind: Service
# metadata:
#   name: flower
#   namespace: finance-dev
# spec:
#   selector:
#     app: flower
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 5555
#       targetPort: 5555
# ---
# # Celery Flower Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flower
#   namespace: finance-dev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: flower
#   template:
#     metadata:
#       labels:
#         app: flower
#     spec:
#       containers:
#       - name: flower
#         image: your-repo/celery-app:{{IMAGE_TAG}}
#         command: ["celery", "-A", "tasks", "flower", "--port=5555"]
#         ports:
#         - containerPort: 5555
#         env:
#         - name: CELERY_BROKER_URL
#           value: "redis://redis-service:6379/0"
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "100m"
#           limits:
#             memory: "256Mi"
#             cpu: "100m"
