apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: finance-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: freenance/celery-app:{{IMAGE_TAG}}
        env:
        - name: CURRENCY_API_KEY
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: CURRENCY_API_KEY
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: DB_PASSWORD
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: CELERY_BROKER_URL
        - name: CURRENCY_TABLE_NAME
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: CURRENCY_TABLE_NAME
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"